steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/mlop-gcp/python-app-repository/mlops-demo-app', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/mlop-gcp/python-app-repository/mlops-demo-app']

# - name: 'asia-south1-docker.pkg.dev/mlop-gcp/python-app-repository/mlops-demo-app-1'
#   entrypoint: 'bash'
#   args:
#    - '-c'
#    - |
#       python -m pytest
  
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
   - 'run'
   - 'deploy'
   - 'mlops-demo-app'
   - '--image'
   - 'asia-south1-docker.pkg.dev/mlop-gcp/python-app-repository/mlops-demo-app'
   - '--region'
   - 'asia-south1'
   - '--allow-unauthenticated'
images:
- 'asia-south1-docker.pkg.dev/mlop-gcp/python-app-repository/mlops-demo-app'

options:
  logging: CLOUD_LOGGING_ONLY
